const uuidv4 = require('uuid').v4;
const between = (min, max) => Math.floor(
  Math.random() * (max - min + 1) + min
)

const converToUuid = (xs) => xs.map((x) => ({ ...x, id: uuidv4() })) 

const BlogItems = [
  {
    id: 0,
    image: '/images/blog-1.jpg',
    title: 'Apple анонсировала iPhone 11',
    date: '11.08.2019',
  },
  {
    id: 1,
    image: '/images/blog-2.jpg',
    title: 'Huawei выпустила умную колонку Sound X с 360-градусным звучанием',
    date: '10.10.2019',
  },
  {
    id: 2,
    image: '/images/blog-3.jpg',
    title: 'Huawei показала новые смартфоны P30 и P30 Pro',
    date: '10.10.2019',
  },
];

const generalSlides = [
  {
    id: 0,
    image: '/images/product-image.jpg',
  },
  {
    id: 1,
    image: '/images/product-image.jpg',
  },
  {
    id: 2,
    image: '/images/product-image.jpg',
  },
  {
    id: 3,
    image: '/images/product-image.jpg',
  },
  {
    id: 4,
    image: '/images/product-image.jpg',
  },
];

const specialOffers = [
  {
    id: 0,
    products: [
      {
        id: 0,
        image: 'images/TV.png',
        productName: 'Philips TV',
        description: 'SMART',
        price: 1199.99,
        likes: 81,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 1,
        image: 'images/airPods.png',
        productName: 'airPods 2',
        description: 'With wireless charging case',
        price: 2649.99,
        tags: [],
        likes: 981,
        installment: 'Рассрочка 12 ay 259 azn',
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 2,
        image: 'images/mac.png',
        productName: 'MacBook Air 13',
        description: 'Gold 2019',
        price: 1200.99,
        tags: [],
        likes: 99,
        installment: 'Рассрочка 12 ay 259 azn',
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 3,
        image: 'images/huawei.png',
        productName: 'Huawei',
        description: 'AI camera',
        price: 2649.99,
        likes: 67,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [
          {
            id: 0,
            color: false,
            text: '-25%',
          },
        ],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
    ],
  },
  {
    id: 1,
    products: [
      {
        id: 0,
        image: 'images/marshall.png',
        productName: 'Philips TV',
        description: 'SMART',
        price: 1199.99,
        likes: 864,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [
          {
            id: 0,
            color: true,
            text: 'NEW',
          },
        ],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 1,
        image: 'images/mac.png',
        productName: 'airPods 2',
        description: 'With wireless charging case',
        price: 2649.99,
        likes: 1010,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 2,
        image: 'images/display.png',
        productName: 'MacBook Air 13',
        description: 'Gold 2019',
        price: 1200.99,
        likes: 878,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 3,
        image: 'images/gopro.png',
        productName: 'Huawei',
        description: 'AI camera',
        price: 2649.99,
        likes: 894,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [
          {
            id: 0,
            color: false,
            text: '6 месяцев 0%',
          },
        ],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    products: [
      {
        id: 0,
        image: 'images/TV.png',
        productName: 'Philips TV',
        description: 'SMART',
        price: 1199.99,
        likes: 893,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 1,
        image: 'images/airPods.png',
        productName: 'airPods 2',
        description: 'With wireless charging case',
        price: 2649.99,
        tags: [],
        likes: 6803,
        installment: 'Рассрочка 12 ay 259 azn',
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 2,
        image: 'images/mac.png',
        productName: 'MacBook Air 13',
        description: 'Gold 2019',
        price: 1200.99,
        likes: 111,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 3,
        image: 'images/huawei.png',
        productName: 'Huawei',
        description: 'AI camera',
        price: 2649.99,
        likes: 908,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [
          {
            id: 0,
            color: false,
            text: '-25%',
          },
        ],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
    ],
  },
  {
    id: 3,
    products: [
      {
        id: 0,
        image: 'images/marshall.png',
        productName: 'Philips TV',
        description: 'SMART',
        price: 1199.99,
        likes: 190,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [
          {
            id: 0,
            color: true,
            text: 'NEW',
          },
        ],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 1,
        image: 'images/mac.png',
        productName: 'airPods 2',
        description: 'With wireless charging case',
        price: 2649.99,
        tags: [],
        likes: 45,
        installment: 'Рассрочка 12 ay 259 azn',
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 2,
        image: 'images/display.png',
        productName: 'MacBook Air 13',
        description: 'Gold 2019',
        price: 1200.99,
        likes: 464,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
      {
        id: 3,
        image: 'images/gopro.png',
        productName: 'Huawei',
        description: 'AI camera',
        price: 2649.99,
        likes: 35,
        installment: 'Рассрочка 12 ay 259 azn',
        tags: [
          {
            id: 0,
            color: false,
            text: '6 месяцев 0%',
          },
        ],
        specs: [
          {
            id: 0,
            specName: 'Размер экрана:',
            spec: '6,3',
          },
          {
            id: 1,
            specName: 'RAM-ROM:',
            spec: '4 ГБ / 64 ГБ',
          },
          {
            id: 2,
            specName: 'Емкость аккумулятора:',
            spec: '6000 мА*ч',
          },
        ],
      },
    ],
  },
];

const newProducts = converToUuid([
  {
    id: 0,
    image: 'images/TV.png',
    productName: 'Philips TV',
    description: 'SMART',
    price: 1199.99,
    likes: 151,
    tags: [],
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 1,
    image: 'images/airPods.png',
    productName: 'airPods 2',
    description: 'With wireless charging case',
    price: 2649.99,
    likes: 6511,
    tags: [],
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 2,
    image: 'images/mac.png',
    productName: 'MacBook Air 13',
    description: 'Gold 2019',
    price: 1200.99,
    likes: 51,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 3,
    image: 'images/huawei.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 91,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '-25%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 4,
    image: 'images/huawei.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 341,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '-25%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 5,
    image: 'images/huawei.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 86,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '-25%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 6,
    image: 'images/huawei.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 91,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '-25%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
]);

const newsSlides = [
  {
    id: 0,
    image: '/images/new-product.jpg',
  },
];

const promotionsSides = [
  {
    id: 0,
    image: '/images/special-product.jpg',
    date: '30 March 2020 14:48 UTC',
  },
];

const salsLeader = [
  {
    id: 0,
    image: 'images/marshall.png',
    productName: 'Philips TV',
    description: 'SMART',
    price: 1199.99,
    likes: 111,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: true,
        text: 'NEW',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 1,
    image: 'images/mac.png',
    productName: 'airPods 2',
    description: 'With wireless charging case',
    price: 2649.99,
    likes: 88,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 2,
    image: 'images/display.png',
    productName: 'MacBook Air 13',
    description: 'Gold 2019',
    price: 1200.99,
    tags: [],
    likes: 98,
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 3,
    image: 'images/gopro.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 76,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '6 месяцев 0%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 4,
    image: 'images/mac.png',
    productName: 'airPods 2',
    description: 'With wireless charging case',
    price: 2649.99,
    tags: [],
    likes: 23,
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 5,
    image: 'images/display.png',
    productName: 'MacBook Air 13',
    description: 'Gold 2019',
    price: 1200.99,
    tags: [],
    likes: 101,
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 6,
    image: 'images/gopro.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 1113,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '6 месяцев 0%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 7,
    image: 'images/mac.png',
    productName: 'airPods 2',
    description: 'With wireless charging case',
    price: 2649.99,
    likes: 911,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 8,
    image: 'images/display.png',
    productName: 'MacBook Air 13',
    description: 'Gold 2019',
    price: 1200.99,
    tags: [],
    likes: 511,
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 9,
    image: 'images/gopro.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 1161,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '6 месяцев 0%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
];

const smallBanners = [
  {
    id: 0,
    image: '/images/banner-2.jpg',
  },
  {
    id: 1,
    image: '/images/banner-3.jpg',
  },
];

const specialProducts = converToUuid([
  {
    id: 0,
    image: 'images/marshall.png',
    productName: 'Philips TV',
    description: 'SMART',
    price: 1199.99,
    likes: 111,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: true,
        text: 'NEW',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 1,
    image: 'images/mac.png',
    productName: 'airPods 2',
    description: 'With wireless charging case',
    price: 2649.99,
    likes: 23,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 2,
    image: 'images/display.png',
    productName: 'MacBook Air 13',
    description: 'Gold 2019',
    price: 1200.99,
    likes: 101,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 3,
    image: 'images/gopro.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 67,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '6 месяцев 0%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 4,
    image: 'images/mac.png',
    productName: 'airPods 2',
    description: 'With wireless charging case',
    price: 2649.99,
    tags: [],
    likes: 23,
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 5,
    image: 'images/display.png',
    productName: 'MacBook Air 13',
    description: 'Gold 2019',
    price: 1200.99,
    likes: 11,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 6,
    image: 'images/gopro.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 55,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '6 месяцев 0%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 7,
    image: 'images/mac.png',
    productName: 'airPods 2',
    description: 'With wireless charging case',
    price: 2649.99,
    likes: 22,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 8,
    image: 'images/display.png',
    productName: 'MacBook Air 13',
    description: 'Gold 2019',
    price: 1200.99,
    tags: [],
    likes: 67,
    installment: 'Рассрочка 12 ay 259 azn',
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 9,
    image: 'images/gopro.png',
    productName: 'Huawei',
    description: 'AI camera',
    price: 2649.99,
    likes: 34,
    installment: 'Рассрочка 12 ay 259 azn',
    tags: [
      {
        id: 0,
        color: false,
        text: '6 месяцев 0%',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
]);

const SubMenuCategories = [
  {
    id: 0,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 1,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам1',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 2,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам2',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 3,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 1,
        name: 'Хиты продаж3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 2,
        name: 'По цене3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 3,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 4,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 5,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 6,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 7,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 8,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 9,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 10,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 11,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 12,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 13,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 14,
        name: 'Аксессуары3',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 4,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам4',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 1,
        name: 'Хиты продаж4',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 2,
        name: 'По цене4',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 3,
        name: 'Аксессуары4',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 5,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам5',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 1,
        name: 'Хиты продаж5',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 2,
        name: 'По цене5',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 3,
        name: 'Аксессуары5',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 6,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам6',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 1,
        name: 'Хиты продаж6',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 2,
        name: 'По цене6',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 3,
        name: 'Аксессуары6',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 7,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам7',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 1,
        name: 'Хиты продаж7',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 2,
        name: 'По цене7',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 3,
        name: 'Аксессуары7',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 8,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам8',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 1,
        name: 'Хиты продаж8',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
      },
      {
        id: 2,
        name: 'По цене88',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 3,
        name: 'Аксессуары8',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
  {
    id: 9,
    subCategories: [
      {
        id: 0,
        name: 'По Брендам8',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 1,
        name: 'Хиты продаж8',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
      },
      {
        id: 2,
        name: 'По цене88',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
      {
        id: 3,
        name: 'Аксессуары8',
        products: [
          { name: 'Мясорубки', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Гриль', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Комбайны', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Измельчители', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Чайники', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Пароварки', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
          { name: 'Индукционные плиты', img: '/images/1034980_ufo_eco_mini_1500w_5_2@2x.png' },
          { name: 'Чайники', img: '/images/_ariston_abs_vls_evo_wi-fi_pw_50_1_2@2x.png' },
          { name: 'Чайники', img: '/images/1457064_vestfrost_vfc09va_13@2x.png' },
          { name: 'Чайники', img: '/images/ardesto_ofh-11x1@2x.png' },
          { name: 'Чайники', img: '/images/1368468_perfezza_peh-2077_8@2x.png' },
        ].map((item, id) => ({ ...item, id })),
        img: '/images/1275783_roda_aqua_inox_9@2x.png',
      },
    ],
  },
];

const wideBanners = [
  {
    id: 0,
    image: '/images/banner-1.jpg',
  },
  {
    id: 1,
    image: '/images/banner-1.jpg',
  },
];

const mostPopularProducts = converToUuid([
  {
    id: 0,
    image: 'images/TV.png',
    productName: 'Philips TV',
    price: 1199.99,
    slug: 'apple-iphone-11',
    description: 'Pro 15',
    tags: [
      {
        id: 0,
        color: true,
        text: 'NEW',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 1,
    image: 'images/mac.png',
    productName: 'MacBook Air 13',
    price: 1200.99,
    slug: 'apple-MacBook-11',
    description: '64GB Black',
    tags: [
      {
        id: 0,
        color: true,
        text: 'NEW',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 2,
    image: 'images/mac.png',
    productName: 'MacBook Air 13',
    price: 1200.99,
    slug: 'apple-MacBook-11',
    description: '64GB Black',
    tags: [
      {
        id: 0,
        color: true,
        text: 'NEW',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
  {
    id: 3,
    image: 'images/marshall.png',
    productName: 'Philips TV',
    price: 1199.99,
    slug: 'Philips-TV',
    description: '64GB Black',
    tags: [
      {
        id: 0,
        color: true,
        text: 'NEW',
      },
    ],
    specs: [
      {
        id: 0,
        specName: 'Размер экрана:',
        spec: '6,3',
      },
      {
        id: 1,
        specName: 'RAM-ROM:',
        spec: '4 ГБ / 64 ГБ',
      },
      {
        id: 2,
        specName: 'Емкость аккумулятора:',
        spec: '6000 мА*ч',
      },
    ],
  },
]);

const categories = [
  {
    id: 0,
    image: '/images/huawei.png',
    title: 'Смартфони',
    href: '/category',
    productNames: [
      {
        product: 'Samsung',
        id: 0,
        href: '/category',
      },
      {
        product: 'Xiaomi',
        id: 1,
        href: '/category',
      },
      {
        product: 'Apple',
        id: 2,
        href: '/category',
      },
      {
        product: 'Huawei',
        id: 3,
        href: '/category',
      },
      {
        product: 'Honor',
        id: 4,
        href: '/category',
      },
      {
        product: 'Vivo',
        id: 5,
        href: '/category',
      },
      {
        product: 'Google',
        id: 6,
        href: '/category',
      },
      {
        product: 'Asus',
        id: 7,
        href: '/category',
      },
      {
        product: 'OnePlus',
        id: 8,
        href: '/category',
      },
      {
        product: 'ZTE',
        id: 9,
        href: '/category',
      },
    ],
  },
  {
    id: 1,
    image: '/images/tablet.png',
    title: 'Планшеты',
    href: '/category',
    productNames: [
      {
        product: 'Samsung',
        id: 10,
        href: '/category',
      },
      {
        product: 'Xiaomi',
        id: 11,
        href: '/category',
      },
      {
        product: 'Apple',
        id: 12,
        href: '/category',
      },
      {
        product: 'Huawei',
        id: 13,
        href: '/category',
      },
      {
        product: 'Honor',
        id: 14,
        href: '/category',
      },
      {
        product: 'Vivo',
        id: 15,
        href: '/category',
      },
      {
        product: 'Google',
        id: 16,
        href: '/category',
      },
      {
        product: 'Asus',
        id: 17,
        href: '/category',
      },
      {
        product: 'OnePlus',
        id: 18,
        href: '/category',
      },
      {
        product: 'ZTE',
        id: 19,
        href: '/category',
      },
    ],
  },
  {
    id: 2,
    image: '/images/bank.png',
    title: 'Аксесуары',
    href: '/category',
    productNames: [
      {
        product: 'Samsung',
        id: 20,
        href: '/category',
      },
      {
        product: 'Xiaomi',
        id: 21,
        href: '/category',
      },
      {
        product: 'Apple',
        id: 22,
        href: '/category',
      },
      {
        product: 'Huawei',
        id: 23,
        href: '/category',
      },
      {
        product: 'Honor',
        id: 24,
        href: '/category',
      },
      {
        product: 'Vivo',
        id: 25,
        href: '/category',
      },
      {
        product: 'Google',
        id: 26,
        href: '/category',
      },
      {
        product: 'Asus',
        id: 27,
        href: '/category',
      },
      {
        product: 'OnePlus',
        id: 28,
        href: '/category',
      },
      {
        product: 'ZTE',
        id: 29,
        href: '/category',
      },
    ],
  },
  {
    id: 3,
    image: '/images/band.png',
    title: 'Смарт браслеты',
    href: '/category',
    productNames: [
      {
        product: 'Samsung',
        id: 30,
        href: '/category',
      },
      {
        product: 'Xiaomi',
        id: 31,
        href: '/category',
      },
      {
        product: 'Apple',
        id: 32,
        href: '/category',
      },
      {
        product: 'Huawei',
        id: 33,
        href: '/category',
      },
      {
        product: 'Honor',
        id: 34,
        href: '/category',
      },
      {
        product: 'Vivo',
        id: 35,
        href: '/category',
      },
      {
        product: 'Google',
        id: 36,
        href: '/category',
      },
      {
        product: 'Asus',
        id: 37,
        href: '/category',
      },
      {
        product: 'OnePlus',
        id: 38,
        href: '/category',
      },
      {
        product: 'ZTE',
        id: 39,
        href: '/category',
      },
    ],
  },
  {
    id: 4,
    image: '/images/amazfit.png',
    title: 'Смарт часы',
    href: '/category',
    productNames: [
      {
        product: 'Samsung',
        id: 40,
        href: '/category',
      },
      {
        product: 'Xiaomi',
        id: 41,
        href: '/category',
      },
      {
        product: 'Apple',
        id: 42,
        href: '/category',
      },
      {
        product: 'Huawei',
        id: 43,
        href: '/category',
      },
      {
        product: 'Honor',
        id: 44,
        href: '/category',
      },
      {
        product: 'Vivo',
        id: 45,
        href: '/category',
      },
      {
        product: 'Google',
        id: 46,
        href: '/category',
      },
      {
        product: 'Asus',
        id: 47,
        href: '/category',
      },
      {
        product: 'OnePlus',
        id: 48,
        href: '/category',
      },
      {
        product: 'ZTE',
        id: 49,
        href: '/category',
      },
    ],
  },
  {
    id: 5,
    image: '/images/aspiring.png',
    title: 'Аксессуары для автомобиля',
    href: '/category',
    productNames: [
      {
        product: 'Samsung',
        id: 50,
        href: '/category',
      },
      {
        product: 'Xiaomi',
        id: 51,
        href: '/category',
      },
      {
        product: 'Apple',
        id: 52,
        href: '/category',
      },
      {
        product: 'Huawei',
        id: 53,
        href: '/category',
      },
      {
        product: 'Honor',
        id: 54,
        href: '/category',
      },
      {
        product: 'Vivo',
        id: 55,
        href: '/category',
      },
      {
        product: 'Google',
        id: 56,
        href: '/category',
      },
      {
        product: 'Asus',
        id: 57,
        href: '/category',
      },
      {
        product: 'OnePlus',
        id: 58,
        href: '/category',
      },
      {
        product: 'ZTE',
        id: 59,
        href: '/category',
      },
    ],
  },
  {
    id: 6,
    image: '/images/sim.png',
    title: 'Номера',
    href: '/category',
    productNames: [
      {
        product: 'Samsung',
        id: 60,
        href: '/category',
      },
      {
        product: 'Xiaomi',
        id: 61,
        href: '/category',
      },
      {
        product: 'Apple',
        id: 62,
        href: '/category',
      },
      {
        product: 'Huawei',
        id: 63,
        href: '/category',
      },
      {
        product: 'Honor',
        id: 64,
        href: '/category',
      },
      {
        product: 'Vivo',
        id: 65,
        href: '/category',
      },
      {
        product: 'Google',
        id: 66,
        href: '/category',
      },
      {
        product: 'Asus',
        id: 67,
        href: '/category',
      },
      {
        product: 'OnePlus',
        id: 68,
        href: '/category',
      },
      {
        product: 'ZTE',
        id: 69,
        href: '/category',
      },
    ],
  },
];

const categorySlides = [
  {
    id: 0,
    image: '/images/category_slide.jpg',
  },
  {
    id: 1,
    image: '/images/category_slide.jpg',
  },
  {
    id: 2,
    image: '/images/category_slide.jpg',
  },
  {
    id: 3,
    image: '/images/category_slide.jpg',
  },
  {
    id: 4,
    image: '/images/category_slide.jpg',
  },
];


module.exports = {
  newProducts,
  specialProducts,
  mostPopularProducts,
  BlogItems,
  promotionsSides,
  salsLeader,
  smallBanners,
  SubMenuCategories,
  wideBanners,
  newsSlides,
  generalSlides,
  specialOffers,
  categories,
  categorySlides,
  products: [
    ...newProducts,
    ...specialProducts,
    ...mostPopularProducts
  ].map((x) => ({
    ...x, 
    category: { 
      id: uuidv4(),
      name: ['phone', 'tv', 'service'][between(0, 2)], 
    } 
  }))
};
